### ISSUE TITLE
Understand why MICADo do not call any alteration on the sample with 1000reads, but does so for the with 750reads

### ISSUE THREAD

**Issue by massyah** [cbib/MICADo#17]
- These were generated by the read sampler
- They contain the exact same alteration 
- For the sample with 1000 reads, MICADo do not test for the ref vs alt TAACAGTTCCTGCATGGGCGGCATGAACCGGAGGCCC vs alt TAACAGTTCCTGCATGGGTGGCATGAACCGGAGGCCC

Note that the same apply for several other synthetic samples. 
Run logs are attached: 

[micado_log_C_SYNTHP53_43735_700_035_1_1-1-1.txt](https://github.com/cbib/MICADo/files/53306/micado_log_C_SYNTHP53_43735_700_035_1_1-1-1.txt)

[micado_log_C_SYNTHP53_43735_1000_035_1_1-1-1.txt](https://github.com/cbib/MICADo/files/53307/micado_log_C_SYNTHP53_43735_1000_035_1_1-1-1.txt)

**Comment by massyah** [comment]
Expected mutation is 
Ref: TAACAGTTCCTGCATGGG C GGCATGAACCGGAGGCCC vs 
Alt:  TAACAGTTCCTGCATGGG T GGCATGAACCGGAGGCCC

**Comment by massyah** [comment]
Might be related to issue #18

**Comment by JRudewicz** [comment]
watch issue #18
